
return {
    categories = {
        framework = {
            "es_extended",
            "qbx_core",
            "qb-core",
        },
        inventory = {
            "ak47_qb_inventory",
            "ak47_inventory",
            "jaksam_inventory",
            "qs-inventory",
            "ps-inventory",
            "origen_inventory",
            "codem-inventory",
            "core_inventory",
            "lj-inventory",
            "jpr-inventory",
            "tgiann-inventory",
            "one_inventory",
            "ox_inventory",
            "qb-inventory",
        },
        target = {
            "lation_interact",
            "sleepless_interact",
            "ox_target",
            "qb-target",
        },
        dispatch = {
            "cd_dispatch",
            "ps-dispatch",
            "qs-dispatch",
            "rcore_dispatch",
            "l2s-dispatch",
            "fd_dispatch",
            "emergencydispatch",
            "linden_outlawalert",
            "lb-tablet",
            "origen_police",
            "redutzu-mdt",
            "kartik-mdt",
            "bub-mdt",
            "wasabi_mdt",
            "tk_dispatch",
            "dusa_dispatch",
            "piotreq_gpt",
        },
        fuel = {
            "ox_fuel",
            "LegacyFuel",
            "Renewed-Fuel",
            "cdn-fuel",
            "lc_fuel",
            "ps-fuel",
            "qb-fuel",
            "qs-fuelstations",
            "rcore_fuel",
            "okokGasStation",
            "ti_fuel",
            "x-fuel",
            "esx-sna-fuel",
            "frkn-fuelstationv4",
            "bigDaddy-Fuel",
        },
        phone = {
            "sd-phone",
            "sky_phone",
            "gksphone",
            "jpr-phonesystem",
            "yseries",
            "yphone",
            "yflip-phone",
            "lb-phone",
        },
        keys = {
            "p_vehiclekeys",
            "qbx_vehiclekeys",
            "qb-vehiclekeys",
            "qs-vehiclekeys",
            "Renewed-Vehiclekeys",
            "MrNewbVehicleKeys",
            "wasabi_carlock",
            "tgiann-hotwire",
            "mk_vehiclekeys",
            "brutal_keys",
            "0r-vehiclekeys",
            "mono_carkeys",
            "p_carkeys",
            "vehicles_keys",
            "F_RealCarKeysSystem",
            "bhd_garage",
            "cd_garage",
            "okokGarage",
        },
        hud = {
            "jg-hud",
            "codem-supreme-hud",
            "Codem-BlackHUDV2",
            "mHud",
            "mhud",
            "17mov_Hud",
            "0r-hud-v3",
            "qs-interface",
            "vms_hud",
            "izzy-hudv8",
            "izzy-hudv6",
            "izzy-hudv5",
            "wais-hudv6",
            "wais-hudv5",
            "ak47_hud",
            "dusa_hud",
            "envi-hud",
            "rhud",
            "cx-hud",
            "gfx-hud_aty",
            "tgiann-lumihud",
            "17mov_Interface",
            "ZSX_UIV2",
            "ZSX_UI",
            "tgiann-hud",
            "esx_hud",
            "qbx_hud",
        },
    },

    category_order = { "framework", "inventory", "target", "dispatch", "fuel", "keys", "phone", "hud" },

    required = {
        framework = true,
        inventory = true,
        target    = true,
    },

    client_only = {
        target = true,
    },

    modules = {
        "print",
        "scriptcache",
        "db",
        "util",
        "blip",
        "camera",
        "display",
        "menu",
        "items",
        "nui",
        "pedManager",
        "player",
        "popup",
        "minigames",
        "vehicleManager",
        "vehicles",
    },
}
